server:
  port: 5672
spring:
  profiles: dev
  rabbitmq:
    endpoint: amqp://dataforlife:dataforlife2018@51.38.185.206:5672/myvhost
    exchange: logs
    queue: influxData
   influxdb:
      url: http://localhost:8086
      username: user
      password: ~
      database: test
      retention-policy: autogen